# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02f44c6ea56507349e7a1acc7395fdf2801cbebf0b5c0f90bedc067c4b83d16bba0dd43d8b8252aef21b75f53c52e46b7b905228b0336558274c2370516f209b

test:
  secret_key_base: 9a5144ca21b4479486da36641523ef8b4bede609fed01a7b8816f9c03fce4098a3d1fb30103be46f0f883b4e11112ca904dbb5da33f69e5177818c7c03a2aef8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
